services:
  discord-bot:
    build: ./discord-bot
    networks:
      - griffith-connect
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - griffith-connect
  
networks:
  griffith-connect: