services:
  discord:
    build: ./discord
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - redis
  puppeteer:
    build: ./puppeteer
    env_file:
      - ./.env
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - redis
    cap_add:
      - SYS_ADMIN
    security_opt: 
      - seccomp=unconfined
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
