services:
  discord-bot:
    build: ./discord-bot
    restart: unless-stopped
    depends_on:
      - redis
    # networks:
    #   - griffith-connect
  redis:
    image: redis:latest
    restart: unless-stopped
    # networks:
    #   - griffith-connect
  
# networks:
#   griffith-connect: